### PR TITLE
Add contributing.md and github templates

### PR DESCRIPTION
**Pull request by thaJeztah**
Communicate the current status of this repository.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @alexmavr @dhiltgen @dperny PTAL (I think this was the reason behind the "maintainance notice", so I tried to rephrase it a bit 😇)

/cc @vdemeester 🤗 🐱

**Comment by dperny** [comment]
LGTM, but if you wanted to delete one of the newlines around the stricken line, that would be a bonus. I'll merge without it if you're not feeling like grabbing a computer again soon though.

**Comment by thaJeztah** [comment]
> one of the newlines around the stricken line

Erm, which newlines would you like to have removed? Could you point them out inline? 🤗

**Comment by thaJeztah** [comment]
I'll be back at my computer later tonight, so can update then

**Comment by dperny** [comment]
I just did it myself, forgot I could do that.

**Pull request merged**
